config/routes.rb
Rails.application.routes.draw do
  root 'todos#home'
  resources :todos
  get '/completed', to: 'todos#completed_index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def home

  end

  def index
    @todos = Todo.all
  end

  def completed_index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])

  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save()
      redirect_to todos_path
    else
      render :new
    end
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :priority, :complete, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/completed_index.html.erb
<h1>Completed Tasks</h1>

<% @todos.each do |todo| %>
  <% if todo.complete? %>
    <%= link_to todo.title, todo_path(todo) %>
    <%= link_to 'Edit', edit_todo_path(todo) %>
    <%= link_to 'Delete', todo_path(todo),
          method: :delete,
          data: { confirm: 'Really Delete?'} %>
  <% end %>
  <br/>
<% end %>


<%= link_to 'All Tasks', todos_path %>

app/views/todos/edit.html.erb
<h1>Edit Task</h1>
<%= form_for @todo do |f| %>
  <%= f.label :task %>
  <%= f.text_field :title, required: true %>
  <br/>
  <%= f.label :priority %>
  <%= f.radio_button :priority, 'low', :checked => true %>
  <%= f.label :low %>
  <%= f.radio_button :priority, 'mild', :checked => false %>
  <%= f.label :mild %>
  <%= f.radio_button :priority, 'medium', :checked => false %>
  <%= f.label :medium %>
  <%= f.radio_button :priority, 'high', :checked => false %>
  <%= f.label :high %>
  <%= f.radio_button :priority, 'urgent', :checked => false %>
  <%= f.label :urgent %>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>

<% end %>

app/views/todos/home.html.erb
<h1>Welcome, Traveler</h1>
<%= link_to 'Tasks', todos_path %>

app/views/todos/index.html.erb
<h1>To Do</h1>
<% if @todos.any? %>
  <% @todos.each do |todo| %>
    <h3>
      <%= link_to todo.title, todo_path(todo) %>
      <% case todo.priority %>
        <% when 'mild' %>
          !
        <% when 'medium' %>
          !!
        <% when 'high' %>
          !!!
        <% when 'urgent' %>
          !!!!!
      <% end %>
      <% if todo.complete %>
        <%= '√' %>
      <% end %>
      <%= link_to 'Edit', edit_todo_path(todo) %>
      <%= link_to 'Delete', todo_path(todo),
            method: :delete,
            data: { confirm: 'Really Delete?'} %>
    </h3>
  <% end %>

  <% else %>
  <h4> Nothing to do!</h4>
<% end %>

<%= link_to 'New Task', new_todo_path, class: 'btn' %>
<%= link_to 'Completed Tasks', completed_path %>
<%= link_to 'Home', root_path %>

app/views/todos/new.html.erb
<h1>New Task</h1>
<%= form_for @todo do |f| %>
  <%= f.label :task %>
  <%= f.text_field :title, required: true %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Task</h1>
<blockquote>
  <%= @todo.title %>
  <br/>
  <%= @todo.description %>
  <br/>
  <i>priority: <%= @todo.priority %></i>
  <br/>
  <i>complete:
    <% if @todo.complete %>
      yes
    <% else %>
      no
    <% end %>
    </i>
</blockquote>

<div class = 'action buttons'>
  <%= link_to 'Edit', edit_todo_path(@todo) %>
  <%= link_to 'Delete', todo_path(@todo),
        method: :delete,
        data: { confirm: 'Really Delete?'} %>
  <%= link_to 'All Tasks', todos_path %>
</div>